thenable Namespace Reference
Namespaces
 experimental
Classes
class ThenableFuture
class ThenablePromise
class ThenableSharedFuture
Typedefs
template<typename Functor , typename FutureType >
using implicit_result_of = decltype(detail::then_helper< typename detail::get_future_type< typename std::remove_reference< FutureType >::type >::type, Functor >::dispatch(std::forward< FutureType >(std::declval< FutureType >()), std::forward< Functor >(std::declval< Functor >())))
template<typename Functor >
using recursive_result_of = typename detail::recursive_get_future_type< typename std::result_of< Functor()>::type >::type
Enumerations
enum then_launch { then_launch::detached = 4
 }
Functions
template<typename... Results>
std::future< std::tuple< Results... > > await_all (std::tuple< std::future< Results >... > &&results, std::launch policy=default_policy)
template<typename... Results>
std::future< std::tuple< Results... > > await_all (std::tuple< std::shared_future< Results >... > &&results, std::launch policy=default_policy)
template<typename... Results>
ThenableFuture< std::tuple< Results... > > await_all (std::tuple< ThenableFuture< Results >... > &&results, std::launch policy=default_policy)
template<typename... Results>
ThenableFuture< std::tuple< Results... > > await_all (std::tuple< ThenableSharedFuture< Results >... > &&results, std::launch policy=default_policy)
template<typename... Results>
std::future< std::tuple< Results... > > await_all (std::tuple< std::promise< Results >... > &&results, std::launch policy=default_policy)
template<typename... Results>
ThenableFuture< std::tuple< Results... > > await_all (std::tuple< ThenablePromise< Results >... > &&results, std::launch policy=default_policy)
template<typename... Results>
std::future< std::tuple< Results... > > await_all (std::tuple< std::future< Results >... > &&results, then_launch policy)
template<typename... Results>
std::future< std::tuple< Results... > > await_all (std::tuple< std::shared_future< Results >... > &&results, then_launch policy)
template<typename... Results>
ThenableFuture< std::tuple< Results... > > await_all (std::tuple< ThenableFuture< Results >... > &&results, then_launch policy)
template<typename... Results>
ThenableFuture< std::tuple< Results... > > await_all (std::tuple< ThenableSharedFuture< Results >... > &&results, then_launch policy)
template<typename... Results>
std::future< std::tuple< Results... > > await_all (std::tuple< std::promise< Results >... > &&results, then_launch policy)
template<typename... Results>
ThenableFuture< std::tuple< Results... > > await_all (std::tuple< ThenablePromise< Results >... > &&results, then_launch policy)
template<typename Functor , typename... Args>
std::future< typename std::result_of< Functor(Args...)>::type > defer (Functor &&f, Args &&...args)
template<typename Functor , typename... Args>
ThenableFuture< typename std::result_of< Functor(Args...)>::type > defer2 (Functor &&f, Args &&...args)
template<typename T = void, typename Functor , typename LaunchPolicy = std::launch>
std::future< T > make_promise (Functor &&, LaunchPolicy=default_policy)
template<typename T = void, typename Functor , typename LaunchPolicy = std::launch>
ThenableFuture< T > make_promise2 (Functor &&, LaunchPolicy=default_policy)
template<typename... Functors>
std::tuple< std::future< recursive_result_of< Functors > >... > parallel (Functors &&...fns)
template<typename... Functors>
std::tuple< ThenableFuture< recursive_result_of< Functors > >... > parallel2 (Functors &&...fns)
template<typename... Functors>
std::tuple< ThenableFuture< recursive_result_of< Functors > >... > parallel2_n (size_t concurrency, Functors &&...fns)
template<typename... Functors>
std::tuple< std::future< recursive_result_of< Functors > >... > parallel_n (size_t concurrency, Functors &&...fns)
template<typename Functor >
std::future< auto > reverse_waterfall (std::launch policy, Functor &&f)
template<typename Functor >
std::future< auto > reverse_waterfall (then_launch policy, Functor &&f)
template<typename PolicyType , typename Functor , typename... Functors>
std::future< auto > reverse_waterfall (PolicyType policy, Functor &&f, Functors &&...fns)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::future< T > > > then (std::future< T > &, Functor &&, std::launch=default_policy)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::shared_future< T > > > then (std::shared_future< T > &&, Functor &&, std::launch=default_policy)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::shared_future< T > > > then (std::shared_future< T >, Functor &&, std::launch=default_policy)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::future< T > > > then (std::future< T > &&, Functor &&, std::launch=default_policy)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::future< T > > > then (std::promise< T > &, Functor &&, std::launch=default_policy)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::future< T > > > then (std::future< T > &, Functor &&, then_launch)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::shared_future< T > > > then (std::shared_future< T > &&, Functor &&, then_launch)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::shared_future< T > > > then (std::shared_future< T >, Functor &&, then_launch)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::future< T > > > then (std::future< T > &&, Functor &&, then_launch)
template<typename T , typename Functor >
std::future< implicit_result_of< Functor, std::future< T > > > then (std::promise< T > &, Functor &&, then_launch)
template<typename FutureType , typename Functor , typename LaunchPolicy >
ThenableFuture< implicit_result_of< Functor, FutureType > > then2 (FutureType &&s, Functor &&f, LaunchPolicy policy)
template<typename FutureType , typename Functor , typename LaunchPolicy >
ThenableFuture< implicit_result_of< Functor, FutureType > > then2 (FutureType &s, Functor &&f, LaunchPolicy policy)
template<typename T >
constexpr ThenableFuture< T > to_thenable (std::future< T > &&)
template<typename T >
constexpr ThenableSharedFuture< T > to_thenable (const std::shared_future< T > &)
template<typename T >
constexpr ThenableSharedFuture< T > to_thenable (std::shared_future< T > &&)
template<typename T >
constexpr ThenablePromise< T > to_thenable (std::promise< T > &&)
template<typename... Results>
constexpr std::tuple< ThenableFuture< Results >... > to_thenable (std::tuple< std::future< Results >... > &&)
template<typename... Results>
constexpr std::tuple< ThenableSharedFuture< Results >... > to_thenable (std::tuple< std::shared_future< Results >... > &&)
template<typename... Results>
constexpr std::tuple< ThenablePromise< Results >... > to_thenable (std::tuple< std::promise< Results >... > &&)
template<typename... Results>
constexpr std::tuple< ThenableFuture< Results >... > to_thenable (std::tuple< ThenableFuture< Results >... > &&)
template<typename... Results>
constexpr std::tuple< ThenableSharedFuture< Results >... > to_thenable (std::tuple< ThenableSharedFuture< Results >... > &&)
template<typename... Results>
constexpr std::tuple< ThenablePromise< Results >... > to_thenable (std::tuple< ThenablePromise< Results >... > &&)
template<typename T >
constexpr ThenableFuture< T > to_thenable (ThenableFuture< T > &&t)
template<typename T >
constexpr ThenableSharedFuture< T > to_thenable (const ThenableSharedFuture< T > &t)
template<typename T >
constexpr ThenableSharedFuture< T > to_thenable (ThenableSharedFuture< T > &&t)
template<typename T >
constexpr ThenablePromise< T > to_thenable (ThenablePromise< T > &&t)
template<typename... Functors>
std::future< auto > waterfall (std::launch policy, Functors &&...fns)
template<typename... Functors>
std::future< auto > waterfall (then_launch policy, Functors &&...fns)
template<typename... Functors>
std::future< auto > waterfall (Functors &&...fns)
template<typename... Args>
std::future< auto > waterfall2 (Args &&...args)
Variables
constexpr std::launch default_policy = std::launch::deferred | std::launch::async
Typedef Documentation
template<typename Functor , typename FutureType > using thenable::implicit_result_of = typedef decltype(detail::then_helper<typename detail::get_future_type<typename std::remove_reference<FutureType>::type>::type, Functor>::dispatch(std::forward<FutureType>(std::declval<FutureType>()), std::forward<Functor>(std::declval<Functor>())))
Definition at line 498 of file thenable.hpp.
template<typename Functor > using thenable::recursive_result_of = typedef typename detail::recursive_get_future_type<typename std::result_of<Functor()>::type>::type
Definition at line 143 of file thenable.hpp.
Enumeration Type Documentation
enum thenable::then_launch [strong]
Enumerator
detached
Definition at line 56 of file thenable.hpp.
Function Documentation
template<typename... Results> std::future<std::tuple<Results...> > thenable::await_all (std::tuple< std::future< Results >... > && results, std::launch policy = default_policy)
Definition at line 1056 of file thenable.hpp.
template<typename... Results> std::future<std::tuple<Results...> > thenable::await_all (std::tuple< std::shared_future< Results >... > && results, std::launch policy = default_policy)
Definition at line 1066 of file thenable.hpp.
template<typename... Results> ThenableFuture<std::tuple<Results...> > thenable::await_all (std::tuple< ThenableFuture< Results >... > && results, std::launch policy = default_policy)
Definition at line 1076 of file thenable.hpp.
template<typename... Results> ThenableFuture<std::tuple<Results...> > thenable::await_all (std::tuple< ThenableSharedFuture< Results >... > && results, std::launch policy = default_policy)
Definition at line 1086 of file thenable.hpp.
template<typename... Results> std::future<std::tuple<Results...> > thenable::await_all (std::tuple< std::promise< Results >... > && results, std::launch policy = default_policy)
Definition at line 1096 of file thenable.hpp.
template<typename... Results> ThenableFuture<std::tuple<Results...> > thenable::await_all (std::tuple< ThenablePromise< Results >... > && results, std::launch policy = default_policy)
Definition at line 1106 of file thenable.hpp.
template<typename... Results> std::future<std::tuple<Results...> > thenable::await_all (std::tuple< std::future< Results >... > && results, then_launch policy)
Definition at line 1118 of file thenable.hpp.
References detached.
template<typename... Results> std::future<std::tuple<Results...> > thenable::await_all (std::tuple< std::shared_future< Results >... > && results, then_launch policy)
Definition at line 1139 of file thenable.hpp.
References detached.
template<typename... Results> ThenableFuture<std::tuple<Results...> > thenable::await_all (std::tuple< ThenableFuture< Results >... > && results, then_launch policy)
Definition at line 1160 of file thenable.hpp.
References detached.
template<typename... Results> ThenableFuture<std::tuple<Results...> > thenable::await_all (std::tuple< ThenableSharedFuture< Results >... > && results, then_launch policy)
Definition at line 1181 of file thenable.hpp.
References detached.
template<typename... Results> std::future<std::tuple<Results...> > thenable::await_all (std::tuple< std::promise< Results >... > && results, then_launch policy)
Definition at line 1203 of file thenable.hpp.
References detached.
template<typename... Results> ThenableFuture<std::tuple<Results...> > thenable::await_all (std::tuple< ThenablePromise< Results >... > && results, then_launch policy)
Definition at line 1224 of file thenable.hpp.
References detached.
template<typename Functor , typename... Args> std::future<typename std::result_of<Functor(Args...)>::type> thenable::defer (Functor && f, Args &&... args) [inline]
Definition at line 207 of file thenable.hpp.
Referenced by defer2(), make_promise(), and make_promise2().
template<typename Functor , typename... Args> ThenableFuture<typename std::result_of<Functor(Args...)>::type> thenable::defer2 (Functor && f, Args &&... args) [inline]
Definition at line 212 of file thenable.hpp.
References defer(), THENABLE_NOEXCEPT, and to_thenable().
template<typename T = void, typename Functor , typename LaunchPolicy = std::launch> std::future< T > thenable::make_promise (Functor && f, LaunchPolicy policy = default_policy)
Definition at line 894 of file thenable.hpp.
References defer(), then(), and THENABLE_NOEXCEPT.
template<typename T = void, typename Functor , typename LaunchPolicy = std::launch> ThenableFuture< T > thenable::make_promise2 (Functor && f, LaunchPolicy policy = default_policy)
Definition at line 907 of file thenable.hpp.
References defer(), then2(), and THENABLE_NOEXCEPT.
template<typename... Functors> std::tuple< std::future< recursive_result_of< Functors > >... > thenable::parallel (Functors &&... fns) [inline]
Definition at line 1037 of file thenable.hpp.
References parallel_n().
Referenced by parallel2().
template<typename... Functors> std::tuple< ThenableFuture< recursive_result_of< Functors > >... > thenable::parallel2 (Functors &&... fns) [inline]
Definition at line 1048 of file thenable.hpp.
References parallel().
template<typename... Functors> std::tuple< ThenableFuture< recursive_result_of< Functors > >... > thenable::parallel2_n (size_t concurrency, Functors &&... fns) [inline]
Definition at line 1042 of file thenable.hpp.
References parallel_n().
template<typename... Functors> std::tuple< std::future< recursive_result_of< Functors > >... > thenable::parallel_n (size_t concurrency, Functors &&... fns)
Definition at line 1012 of file thenable.hpp.
References THENABLE_NOEXCEPT.
Referenced by parallel(), and parallel2_n().
template<typename Functor > std::future<auto> thenable::reverse_waterfall (std::launch policy, Functor && f) [inline]
Definition at line 1284 of file thenable.hpp.
Referenced by reverse_waterfall().
template<typename Functor > std::future<auto> thenable::reverse_waterfall (then_launch policy, Functor && f)
Definition at line 1291 of file thenable.hpp.
References detached.
template<typename PolicyType , typename Functor , typename... Functors> std::future<auto> thenable::reverse_waterfall (PolicyType policy, Functor && f, Functors &&... fns) [inline]
Definition at line 1306 of file thenable.hpp.
References reverse_waterfall(), and then().
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::future< T > > > thenable::then (std::future< T > & s, Functor && f, std::launch policy = default_policy) [inline]
Definition at line 557 of file thenable.hpp.
Referenced by make_promise(), reverse_waterfall(), then(), and then2().
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::shared_future< T > > > thenable::then (std::shared_future< T > && s, Functor && f, std::launch policy = default_policy) [inline]
Definition at line 566 of file thenable.hpp.
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::shared_future< T > > > thenable::then (std::shared_future< T > s, Functor && f, std::launch policy = default_policy) [inline]
Definition at line 573 of file thenable.hpp.
References then().
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::future< T > > > thenable::then (std::future< T > && s, Functor && f, std::launch policy = default_policy)
Definition at line 546 of file thenable.hpp.
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::future< T > > > thenable::then (std::promise< T > & s, Functor && f, std::launch policy = default_policy) [inline]
Definition at line 582 of file thenable.hpp.
References then().
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::future< T > > > thenable::then (std::future< T > & s, Functor && f, then_launch policy) [inline]
Definition at line 623 of file thenable.hpp.
References then().
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::shared_future< T > > > thenable::then (std::shared_future< T > && s, Functor && f, then_launch policy) [inline]
Definition at line 632 of file thenable.hpp.
References detached.
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::shared_future< T > > > thenable::then (std::shared_future< T > s, Functor && f, then_launch policy) [inline]
Definition at line 652 of file thenable.hpp.
References then().
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::future< T > > > thenable::then (std::future< T > && s, Functor && f, then_launch policy)
Definition at line 599 of file thenable.hpp.
References detached.
template<typename T , typename Functor > std::future< implicit_result_of< Functor, std::future< T > > > thenable::then (std::promise< T > & s, Functor && f, then_launch policy) [inline]
Definition at line 661 of file thenable.hpp.
References then().
template<typename FutureType , typename Functor , typename LaunchPolicy > ThenableFuture<implicit_result_of<Functor, FutureType> > thenable::then2 (FutureType && s, Functor && f, LaunchPolicy policy) [inline]
Definition at line 671 of file thenable.hpp.
References then(), and to_thenable().
Referenced by make_promise2(), thenable::ThenablePromise< T >::then(), thenable::ThenableFuture< T >::then(), and thenable::ThenableSharedFuture< T >::then().
template<typename FutureType , typename Functor , typename LaunchPolicy > ThenableFuture<implicit_result_of<Functor, FutureType> > thenable::then2 (FutureType & s, Functor && f, LaunchPolicy policy) [inline]
Definition at line 676 of file thenable.hpp.
References then(), and to_thenable().
template<typename T > constexpr ThenableFuture< T > thenable::to_thenable (std::future< T > && t)
Definition at line 816 of file thenable.hpp.
Referenced by defer2(), then2(), and waterfall2().
template<typename T > constexpr ThenableSharedFuture< T > thenable::to_thenable (const std::shared_future< T > & t)
Definition at line 821 of file thenable.hpp.
template<typename T > constexpr ThenableSharedFuture< T > thenable::to_thenable (std::shared_future< T > && t)
Definition at line 826 of file thenable.hpp.
template<typename T > constexpr ThenablePromise< T > thenable::to_thenable (std::promise< T > && t)
Definition at line 831 of file thenable.hpp.
template<typename... Results> constexpr std::tuple< ThenableFuture< Results >... > thenable::to_thenable (std::tuple< std::future< Results >... > && futures)
Definition at line 860 of file thenable.hpp.
template<typename... Results> constexpr std::tuple< ThenableSharedFuture< Results >... > thenable::to_thenable (std::tuple< std::shared_future< Results >... > && futures)
Definition at line 865 of file thenable.hpp.
template<typename... Results> constexpr std::tuple< ThenablePromise< Results >... > thenable::to_thenable (std::tuple< std::promise< Results >... > && promises)
Definition at line 870 of file thenable.hpp.
template<typename... Results> constexpr std::tuple< ThenableFuture< Results >... > thenable::to_thenable (std::tuple< ThenableFuture< Results >... > && futures)
Definition at line 877 of file thenable.hpp.
template<typename... Results> constexpr std::tuple< ThenableSharedFuture< Results >... > thenable::to_thenable (std::tuple< ThenableSharedFuture< Results >... > && futures)
Definition at line 882 of file thenable.hpp.
template<typename... Results> constexpr std::tuple< ThenablePromise< Results >... > thenable::to_thenable (std::tuple< ThenablePromise< Results >... > && promises)
Definition at line 887 of file thenable.hpp.
template<typename T > constexpr ThenableFuture<T> thenable::to_thenable (ThenableFuture< T > && t)
Definition at line 838 of file thenable.hpp.
template<typename T > constexpr ThenableSharedFuture<T> thenable::to_thenable (const ThenableSharedFuture< T > & t)
Definition at line 843 of file thenable.hpp.
template<typename T > constexpr ThenableSharedFuture<T> thenable::to_thenable (ThenableSharedFuture< T > && t)
Definition at line 848 of file thenable.hpp.
template<typename T > constexpr ThenablePromise<T> thenable::to_thenable (ThenablePromise< T > && t)
Definition at line 853 of file thenable.hpp.
template<typename... Functors> std::future<auto> thenable::waterfall (std::launch policy, Functors &&... fns) [inline]
Definition at line 1345 of file thenable.hpp.
Referenced by waterfall(), and waterfall2().
template<typename... Functors> std::future<auto> thenable::waterfall (then_launch policy, Functors &&... fns) [inline]
Definition at line 1350 of file thenable.hpp.
template<typename... Functors> std::future<auto> thenable::waterfall (Functors &&... fns) [inline]
Definition at line 1355 of file thenable.hpp.
References waterfall().
template<typename... Args> std::future<auto> thenable::waterfall2 (Args &&... args) [inline]
Definition at line 1360 of file thenable.hpp.
References to_thenable(), and waterfall().
Variable Documentation
constexpr std::launch thenable::default_policy = std::launch::deferred | std::launch::async
Definition at line 45 of file thenable.hpp.